require(lattice)
attach(mtcars)
print(splom(mtcars[c(1,3,4,5,6)], main="MTCARS Data"))
print(splom(mtcars[c(1,3,4,6)], main="MTCARS Data"))
print(splom(mtcars[c(1,3,4,6)], col=rainbow(7),main="MTCARS Data"))
detach(mtcars)
attach(rock)
print(splom(rock[c(1,2,3,4)], main="ROCK Data"))
detach(rock)